services:
  app:
    build: .
    container_name: flask-task-manager-app
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    volumes:
      - .:/app

  mysql:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: mypassword
      MYSQL_DATABASE: Healthy
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
