version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_DATABASE: task_manager
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build: .
    container_name: flask-task-manager-app
    ports:
      - "5000:5000"
    depends_on:
      - db

volumes:
  db_data:
