version: '3.9'

services:
  db:
    image: mysql:8.0
    container_name: flask-task-manager-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysecretpassword
      MYSQL_DATABASE: task_manager
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - backend

  app:
    build: .
    container_name: flask-task-manager-app
    restart: always
    environment:
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: mysecretpassword
      MYSQL_DATABASE: task_manager
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - backend

volumes:
  db_data:

networks:
  backend:
    driver: bridge
