services:
  db:
    image: mysql:8.0
    container_name: flask-task-manager-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysecretpassword
      MYSQL_DATABASE: task_manager
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - backend

  app:
    build: .
    container_name: flask-task-manager-app
    restart: always
    ports:
      - "5000:5000"   # כאן אנחנו חושפים רק Flask החוצה
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: mysecretpassword
      DB_NAME: task_manager
    depends_on:
      - db
    networks:
      - backend

volumes:
  db_data:

networks:
  backend:
    driver: bridge
