services:
  mysql_db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mypassword
      MYSQL_DATABASE: task_manager
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  flask-app:
    build: .
    container_name: flask-task-manager-app
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - mysql_db
    environment:
      MYSQL_HOST: mysql_db
      MYSQL_USER: root
      MYSQL_PASSWORD: mypassword
      MYSQL_DATABASE: task_manager

volumes:
  db_data:
