version: "3.8"

services:
  db:
    image: mysql:8
    container_name: task_db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: tasks_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build: .
    container_name: flask_task_manager
    ports:
      - "5000:5000"
    environment:
      DB_HOST: db
      DB_USER: user
      DB_PASS: password
      DB_NAME: tasks_db
    depends_on:
      - db

volumes:
  db_data:
