services:
  mysql_db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_DATABASE: task_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - mysql_db
    environment:
      DB_HOST: mysql_db
      DB_USER: root
      DB_PASSWORD: ""
      DB_NAME: task_db

volumes:
  mysql_data:
