apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  mysql-root-password: cm9vdA==    # "root" base64
  mysql-user: dXNlcg==            # "user" base64
  mysql-password: cGFzc3dvcmQ=    # "password" base64
  mysql-database: dGFza19tYW5hZ2Vy # "task_manager" base64
